# Generated by Django 3.0.8 on 2021-01-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
    ]
